### ISSUE TITLE
How can I subscribe multi plan?

### ISSUE THREAD

**Issue by saucompeng** [cb-vivek/chargebee-checkout-samples#2]
https://github.com/cb-vivek/chargebee-checkout-samples/blob/75207228b968bf2da3955caeeaea359513bf7386/api/front-end/vue/index.html#L56

**Comment by cb-vivek** [comment]
Chargebee currently does not support multiple plans in a subscription. But as a workaround, you can create a $0 plan and multiple addons. (We have a setting not to show $0 line items). Hope this helps.

**Comment by saucompeng** [comment]
Ok, I will try it.
